.TH FREERAMDISK 8 "23 Mar 2005" "freeramdisk" "Free RAM Disk"
.SH NAME
freeramdisk \- frees the memory used by the loadlin ramdisk
.SH SYNOPSIS
.B freeramdisk
.SH DESCRIPTION
.B Freeramdisk
is a very simply utility for freeing up the memory that is used by the
ramdisk which is allocated by loadlin.
.SH OPTIONS
There are none.
.SH FILES
.I /dev/ram
.SH AUTHORS
This no-use manpage is by Lenart Janos <ocsi@debian.org>
